In [1]:
import numpy as np

In [2]:
a = np.ones((1, 2, 3))
a

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [3]:
np.transpose(a, (1, 0, 2))

array([[[1., 1., 1.]],

       [[1., 1., 1.]]])

In [4]:
mat = np.array([[2, 1, 0, 0], [0, 2, 1, 0], [0, 0, 2, 1]])

In [5]:
mat

array([[2, 1, 0, 0],
       [0, 2, 1, 0],
       [0, 0, 2, 1]])

In [6]:
np.reshape(mat, 12)

array([2, 1, 0, 0, 0, 2, 1, 0, 0, 0, 2, 1])

In [7]:
type(mat)

numpy.ndarray

In [8]:
x_shape = tuple(map(int, input().split()))
X = np.fromiter(map(int, input().split()), np.int).reshape(x_shape)
y_shape = tuple(map(int, input().split()))
Y = np.fromiter(map(int, input().split()), np.int).reshape(y_shape)

C:\Users\mrbab\AppData\Local\Temp\ipykernel_22548\4280850326.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.fromiter(map(int, input().split()), np.int).reshape(x_shape)


ValueError: cannot reshape array of size 0 into shape ()

In [ ]:
if x_shape[1] != Y.T.shape[0]:
    print('aaa')
else:
    print("bbb")

In [ ]:
print(X.dot(Y.T))

In [ ]:
from urllib.request import urlopen

f = urlopen('https://stepik.org/media/attachments/lesson/16462/boston_houses.csv')

In [ ]:
arr = np.loadtxt(f, skiprows=1, delimiter=',')

In [ ]:
arr

In [ ]:
print(arr.mean(axis=0))

In [ ]:
x = np.array([[1, 60], [1, 50], [1, 75]])
y = np.array([[10], [7], [12]])

In [ ]:
b = np.linalg.inv(x.T @ x) @ x.T @ y
print(b)


In [ ]:
import urllib

In [ ]:
f = urllib.request.urlopen("https://stepik.org/media/attachments/lesson/16462/boston_houses.csv")  # open file from URL
data = np.loadtxt(f, delimiter=',', skiprows=1)  # load data to work with

In [ ]:
data

In [ ]:
x = data[:, 1:]
y = data[:, [0]]

In [ ]:
x = np.hstack((np.ones(shape=[x.shape[0], 1]), x))
x

In [ ]:
b = np.linalg.inv(x.T @ x) @ x.T @ y

In [ ]:
import regex as re

In [ ]:
print(','.join(map(str, b)))

In [ ]:
print(re.sub(r'[^\w.-]', ' ', ''.join(map(str, b))))

In [79]:
X = np.array([[1, 0.3], [0.4, 0.5], [0.7, 0.8]])
X = np.hstack((np.ones(shape=[X.shape[0], 1]), X))
y = np.array([[1], [1], [0]])
# w = np.array([[0.0, 0.0, 0.0]])
w = np.array([[0.0], [0.0], [0.0]])

In [80]:
X.shape

(3, 3)

In [81]:
y.shape

(3, 1)

In [82]:
w.shape

(3, 1)

In [35]:
X

array([[1. , 1. , 0.3],
       [1. , 0.4, 0.5],
       [1. , 0.7, 0.8]])

In [101]:
def predict(ex: np.array):
    ex = np.reshape(ex, newshape=[3, 1])
    if w.T.dot(ex) > 0:
        return 1
    else:
        return 0

In [18]:
def target(x_f: np.array):
    if x_f[1] == 1 and x_f[2] == 0.3:
        return 1
    elif x_f[1] == 0.4 and x_f[2] == 0.5:
        return 1
    elif x_f[1] == 0.7 and x_f[2] == 0.8:
        return 0

In [102]:
perfect = False
for j in range(3):
    e = X[j]
    # print("e: ")
    # print(e)
    if predict(e) != target(e):

        perfect = False
        # if predict(e) == 0:
        #     w += e
        # if predict(e) == 1:
        #     w -= e
        if predict(e) == 0:
            print("predict(e) == 0:")
            w += e.reshape(-1, 1)
        if predict(e) == 1:
            print("predict(e) == 1:")
            w -= e.reshape(-1, 1)
    print("w:")
    print(w)

w:
[[1. ]
 [1. ]
 [0.3]]
w:
[[1. ]
 [1. ]
 [0.3]]
predict(e) == 1:
w:
[[ 0. ]
 [ 0.3]
 [-0.5]]


In [104]:
class Perceptron():
    def __init__(self, n=1, bias=0):
        self.weights = np.zeros(n)
        self.bias = bias

    def predict(self, vect):
        return (self.weights * vect).sum() + self.bias > 0

    def iter_learn(self, vect, answer):
        prediction = self.predict(vect)
        if prediction != answer:
            if prediction:
                self.weights -= vect
            else:
                self.weights += vect

x = Perceptron(2)
x.iter_learn(np.array([1.0, 0.3]), True)
x.iter_learn(np.array([0.4, 0.5]), True)
x.iter_learn(np.array([0.7, 0.8]), False)

In [105]:
x.weights

array([ 0.3, -0.5])